org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# This Kotlin and Gradle flag to fix Gradle Daemon compile error due to using newest version of Gradle (9.1.0)
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
org.gradle.vfs.watch=false
